version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE
      # So you don't have to use root, but you can if you like
      - MYSQL_USER
      # You can use whatever password you like
      - MYSQL_PASSWORD
      # Password for root access
      - MYSQL_ROOT_PASSWORD
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-weblog:/var/lib/mysql
# Names our volume
volumes:
  my-weblog: