services:
  api:
    container_name: weblog-api
    build:
      context: .
      dockerfile: dockerfile
    dns:
      - 8.8.8.8
    ports:
      - "5000:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./Weblog.API/wwwroot:/app/wwwroot
  db:
    container_name: weblog-db
    image: mysql:5.7
    environment:
       MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
       MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-weblog:/var/lib/mysql
# Names our volume
volumes:
  my-weblog: